name: Node CI

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        node-version: 16

      env:
        SSH_PRIVATE_KEY: ${ {secrets.SSH_PRIVATE_KEY} }
        
        SOURCE: "src/"
        REMOTE_HOST: ${ {secrets.REMOTE_HOST} }
        REMOTE_USER: ${ {secrets.REMOTE_USER} }
        REMOTE_PORT: ${ {secrets.REMOTE_PORT} }
        TARGET: ${ {secrets.TARGET} }