name: Navegantes.com CI
on:
  push:
    branches:
      - main

jobs: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        use: actions/checkout@3
      - name: Deploy para meu hosting 
        use: easingthemes/ssh-deploy@main
          env: 
            SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
            ARGS: "-rltgoDzvO --delete"
            SOURCE: "src/"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
            TARGET: ${{ secrets.REMOTE_HOST }}