name: Node.js CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - run: npm i
    - run: npm run build --if-present
    - run: npm test
    env:
      SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      
      SOURCE: "src/"
      REMOTE_HOST: ${{secrets.REMOTE_HOST}}
      REMOTE_USER: ${{secrets.REMOTE_USER}}
      REMOTE_PORT: ${{secrets.REMOTE_PORT}}
      TARGET: ${{secrets.TARGET}}